### ISSUE TITLE
1.54.1 Fails to open ROMs

### ISSUE THREAD

**Issue by stylophile** [OpenEmu/SNES9x-Core#2]
Upon updating to this version, nothing will open - it fails with message "could not load ROM". I dl'd a fresh copy of 1.54.1 and replaced it, but same issue. I reverted back to 1.53.5 and issue was resolved. I'm on a MBA with Sierra 10.12.4.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/3127

**Comment by clobber** [comment]
Fixed in the SNES9x 1.54.1.1 core update.
