### ISSUE TITLE
OESNESSystemResponderClient.h

### ISSUE THREAD

**Issue by androidfans** [OpenEmu/SNES9x-Core#4]
OESNESSystemResponderClient.h depends on OpenEmu proj. but not OpenEmu-SDK.
and i suggest that OpenEmu should expose the snes9x.conf for some chinese game

**Comment by clobber** [comment]
Not sure what you're talking about regarding the SystemResponderClient, but it's easy to see in our [Snes9x core plugin implementation](https://github.com/OpenEmu/SNES9x-Core/blob/1eb8e8c7a89ead4876e56c36b9421cba65bbcb8f/SNESGameCore.mm#L93) that we do no read settings from snes9x.conf.
