### ISSUE TITLE
SNES Bad Audio Quality

### ISSUE THREAD

**Issue by pinkertonpunk** [OpenEmu/SNES9x-Core#5]
Hey everyone.  Using my new Macbook Air with the M1 chip and trying to play FF2 on OpenEmu and the audio quality is pretty bad.  There is just noise in the background and it makes playing any games really annoying.  I've tried both the SNES9x and BSNES cores and the noise is the same.  Anyone else having a similar issue?  I'm using my Airpods for my headphones and using a 8Bitdo SN30 Pro+ controller through bluetooth as well.

**Comment by clobber** [comment]
> using my Airpods for my headphones

Issues with [Bluetooth audio](https://github.com/OpenEmu/OpenEmu/issues?q=bluetooth+audio) are known bugs with macOS. Not a problem per emulator core.
